# Site settings
title: Midnight Sesh.
header-img: img/home-bg.jpg
email: omarenri@hawaii.edu
description: "Exploring music."
baseurl: ""
url: "http://enriquezm.github.io"
github_username:  enriquezm

# Pagination Settings
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
